<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>NUMPY</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2022-09</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

Le package [**numpy**](https://numpy.org) (contraction de ***Numerical Python***) fournit à Python des outils flexibles et efficaces pour le stockage et la manipulation de données homogènes ordonnées. La documentation complète du package se trouve sur le site officiel [**numpy.org**](https://numpy.org/doc/smatrice/), mais une copie locale est directement disponible dans le menu **`Help`** de JupyterLab, sous le titre ***NumPy Reference***.. Ce notebook a pour objet de faire un tour d'horizon rapide des fonctionnalités les plus utiles de **numpy** dans le cadre d'une utilisation en imagerie numérique. 

L'apport principal du package **numpy** au langage Python consiste en un nouveau conteneur ordonné, appelé **`array`**, qui permet de stocker efficacement des ***données homogènes ordonnées selon plusieurs dimensions***. Le terme "**array**" peut se traduire en français de plusieurs manières : *panoplie, palette, éventail, gamme, collection, table*, mais aucun de ces termes n'inclut la notion de multi-dimensionalité présente dans la nature du conteneur. La traduction la plus proche serait **table**, mais ce terme a une sémantique très forte dans le domaine des bases de données, ce qui risque d'engendrer une confusion. Au final, la traduction par **matrice multi-dimensionnelle** ou **matrice nD** semble la plus cohérente, et c'est celle qui sera utilisée dans ce cours. Pour les matrices de dimension 1, on pourra également employer le terme usuel de **vecteur**.

Le terme "**données homogènes**" signifie que tous les éléments stockés dans un conteneur **`array`** doivent être du même type, ce qui implique que chaque élément occupe exactement le même espace dans la mémoire de l'ordinateur. Par conséquent, en stockant les éléments de manière juxtaposée en mémoire, il est possible d'accéder de manière très efficace à chacun d'eux, par simple décalage par rapport à l'adresse de base de la matrice. A l'inverse, le conteneur **`list`** disponible dans le noyau du langage Python, est une structure destinée à stocker des ***données hétérogènes*** (chaque élément d'une liste peut avoir son type propre) ce qui interdit un stockage compact et un accès efficace aux données individuelles

---
On importe habituellement le package **numpy** par le biais d'un alias court, avec la commande suivante :

> **`import numpy as np`**

In [1]:
import numpy as np # import du package 'numpy' avec alias 'np'

Dans ce notebook, on va également utiliser très fréquemment la fonction **`show`**, qui permet de simplifier grandement certaines explications. Comme il ne s'agit pas d'une fonction standard de Python, il faut commencer par l'importer du module **`tools`** se trouvant dans le dossier **SRC** :

In [2]:
from SRC.tools import show # import de la fonction 'show' du module 'tools' dans le dossier SRC

A la différence de la fonction **`print`** qui n'affiche que la valeur des expressions données en paramètres, la fonction **`show`** permet d'***afficher à la fois l'expression initiale et la valeur de cette expression***, à condition de mettre l'expression entre guillemets. Plusieurs expressions peuvent être évaluées en séquence, en les séparant par des **points virgule**, chacune de ces expressions s'affichera alors sur une ligne séparée

In [3]:
a, b, c, d = 0, '♠ ♣ ♥ ♦', [1, 2, 3], dict(a=1, b=2, c=3)
show("1 + 2 + 3 + 4;; a; b; c; d;; 12**345#")
# chaque caractère ';' génère un retour à la ligne (et donc un ';;' va créer un saut de ligne)
# lorsqu'une valeur est trop longue pour tenir sur une ligne, on peut améliorer la lisibilité en rajoutant
# un suffixe '#' qui va insérer un retour à la ligne entre l'expression et sa valeur 

1 + 2 + 3 + 4 ━► 10

a ━► 0
b ━► ♠ ♣ ♥ ♦
c ━► [1, 2, 3]
d ━► {'a': 1, 'b': 2, 'c': 3}

12**345 ━►
2077446682327378559843444695582704973572786912705232236931705903179519704325276892191015329301807037794598378537132233994613616420526484930777273718077112370160566492728059713895917217042738578562985773221381211423961068296308572143393854703167926779929682604844469621152130457090778409728703018428147734622401526422774317612081074841839507864189781700150115308454681772032


<h2 style="padding:16px; color:#FFF; background:#07D">A - Création de matrices</h2>

### 1 - Création de matrices à partir de listes Python

In [4]:
# création d'une matrice 1D (= vecteur) à partir d'une liste Python
a = np.array([1,-2,3,-4,-5,6,-7,8])

In [5]:
a # affichage par défaut (le préfixe 'array' indique une matrice numpy)

array([ 1, -2,  3, -4, -5,  6, -7,  8])

In [6]:
print(a) # affichage plus compact et plus lisible

[ 1 -2  3 -4 -5  6 -7  8]


In [7]:
show("a") # idem avec la fonction 'show'

a ━► [ 1 -2  3 -4 -5  6 -7  8]


En plus des données brutes stockées dans la matrice, le type **`array`** possède un certain nombre de propriétés, accessibles par la notation pointée :

- **`.ndim`** = nombre de dimensions de la matrice
- **`.shape`** = nombre d'éléments pour chacune des dimensions
- **`.size`** = nombre total d'éléments de la matrice
- **`.itemsize`** = nombre d'octets par élément
- **`.nbytes`** = nombre d'octets pour la matrice
- **`.dtype`** = type de donnée des éléments de la matrice (selon la nomenclature **numpy**)

La liste des types de données utilisables avec numpy se trouve sur **[cette page](https://numpy.org/doc/stable/reference/arrays.dtypes.html)** du manuel de référence.

In [8]:
show("a; a.ndim; a.shape; a.size; a.itemsize; a.nbytes; a.dtype") # propriétés de la matrice

a ━► [ 1 -2  3 -4 -5  6 -7  8]
a.ndim ━► 1
a.shape ━► (8,)
a.size ━► 8
a.itemsize ━► 4
a.nbytes ━► 32
a.dtype ━► int32


In [9]:
# création d'une matrice 1D en forçant le type des éléments
b = np.array([1,-2,3,-4,-5,6,-7,8], dtype=float) # on peut utiliser un type standard
show("b; b.ndim; b.shape; b.size; b.itemsize; b.nbytes; b.dtype;")
c = np.array([1,-2,3,-4,-5,6,-7,8], dtype=np.float32) # ou un type spécifique numpy
show("c; c.ndim; c.shape; c.size; c.itemsize; c.nbytes; c.dtype;")
d = np.array([1,-2,3,-4,-5,6,-7,8], dtype='i2') # ou une chaîne avec la notation courte
show("d; d.ndim; d.shape; d.size; d.itemsize; d.nbytes; d.dtype")

b ━► [ 1. -2.  3. -4. -5.  6. -7.  8.]
b.ndim ━► 1
b.shape ━► (8,)
b.size ━► 8
b.itemsize ━► 8
b.nbytes ━► 64
b.dtype ━► float64

c ━► [ 1. -2.  3. -4. -5.  6. -7.  8.]
c.ndim ━► 1
c.shape ━► (8,)
c.size ━► 8
c.itemsize ━► 4
c.nbytes ━► 32
c.dtype ━► float32

d ━► [ 1 -2  3 -4 -5  6 -7  8]
d.ndim ━► 1
d.shape ━► (8,)
d.size ━► 8
d.itemsize ━► 2
d.nbytes ━► 16
d.dtype ━► int16


In [10]:
# création d'une matrice 2D à partir d'une liste de listes
a = np.array([[1,-2,3,-4], [-5,6,-7,8]])
show("a#; a.ndim; a.shape; a.size; a.itemsize; a.nbytes; a.dtype")

a ━►
[[ 1 -2  3 -4]
 [-5  6 -7  8]]
a.ndim ━► 2
a.shape ━► (2, 4)
a.size ━► 8
a.itemsize ━► 4
a.nbytes ━► 32
a.dtype ━► int32


In [11]:
# création d'une matrice 2D en forçant le type des éléments
b = np.array([[1,-2,3,-4], [-5,6,-7,8]], dtype=str) # on peut utiliser le type standard 'str'
# dans ce cas, la taille commune aux éléments de la matrice est calculée automatiquement
show("b#; b.ndim; b.shape; b.size; b.itemsize; b.nbytes; b.dtype;")
c = np.array([[1,-2,3,-4], [-5,6,-7,8]], dtype='U6') # on peut utiliser le type 'U' (unicode)
# dans ce cas, on définit explicitement une taille fixe pour les éléments de la matrice
show("c#; c.ndim; c.shape; c.size; c.itemsize; c.nbytes; c.dtype")

b ━►
[['1' '-2' '3' '-4']
 ['-5' '6' '-7' '8']]
b.ndim ━► 2
b.shape ━► (2, 4)
b.size ━► 8
b.itemsize ━► 8
b.nbytes ━► 64
b.dtype ━► <U2

c ━►
[['1' '-2' '3' '-4']
 ['-5' '6' '-7' '8']]
c.ndim ━► 2
c.shape ━► (2, 4)
c.size ━► 8
c.itemsize ━► 24
c.nbytes ━► 192
c.dtype ━► <U6


---
### 2 - Création de matrices à l'aide de fonctions génératrices

In [12]:
print(np.zeros((3,5))) # création d'une matrice initialisée à 0 (type 'float' par défaut)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
print(np.zeros((3,5), dtype=int)) # idem en forçant le type à 'int'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
print(np.zeros_like(a)) # création d'une matrice de 0 à partir d'une matrice existante

[[0 0 0 0]
 [0 0 0 0]]


In [15]:
print(np.ones((2,3,6))) # création d'une matrice initialisée à 1

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [16]:
print(np.ones_like(a)) # création d'une matrice de 1 à partir d'une matrice existante

[[1 1 1 1]
 [1 1 1 1]]


In [17]:
print(np.full((3,2,12), 'x')) # création d'une matrice initialisée à une valeur donnée

[[['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']]

 [['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']]

 [['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']]]


In [18]:
print(np.full_like(a, 999)) # création d'une matrice initialisée à partir d'une matrice existante

[[999 999 999 999]
 [999 999 999 999]]


---

In [19]:
print(np.eye(3)) # création d'une matrice identité de taille 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.tri(5)) # création d'une matrice triangulaire sur base carrée

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [21]:
print(np.tri(4,8)) # création d'une matrice triangulaire sur base rectangulaire

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]


In [22]:
print(np.tri(6,9,2)) # création d'une matrice triangulaire avec décalage de diagonale

[[1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [23]:
print(np.arange(99,0,-11)) # création d'une matrice à partir d'un itérateur à pas entiers

[99 88 77 66 55 44 33 22 11]


In [24]:
print(np.linspace(0,1,11)) # idem avec un itérateur à pas linéaires

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [25]:
# création d'une matrice de valeurs aléatoires entières sur {1..6}
print(np.random.randint(1, 7, (4,32))) # intervalle de valeurs, fermé à gauche, ouvert à droite

[[6 5 4 1 4 4 6 6 1 6 6 3 2 5 2 6 3 3 4 3 1 1 5 4 5 4 3 5 1 6 6 3]
 [1 5 4 6 3 3 3 5 4 2 2 3 6 6 2 2 1 3 5 2 3 3 1 6 4 3 3 1 5 4 2 2]
 [5 4 5 3 4 1 1 5 3 4 5 5 5 3 5 3 5 4 3 5 2 1 2 1 5 2 6 6 5 3 2 5]
 [1 5 1 2 3 4 6 3 2 1 3 4 5 4 5 1 3 3 5 2 1 6 2 5 5 4 1 2 4 2 6 1]]


In [26]:
# création d'une matrice obtenue par tirage aléatoire dans un ensemble
print(np.random.choice(list('ABC'), (6,16), p=(0.6,0.3,0.1))) # p = probas

[['A' 'A' 'B' 'B' 'B' 'A' 'A' 'C' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'B']
 ['B' 'C' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'A' 'A' 'B' 'B' 'B' 'A' 'B']
 ['B' 'B' 'B' 'B' 'A' 'A' 'B' 'A' 'B' 'B' 'C' 'B' 'A' 'A' 'A' 'B']
 ['B' 'A' 'B' 'A' 'A' 'B' 'A' 'A' 'A' 'B' 'A' 'B' 'B' 'A' 'A' 'B']
 ['A' 'C' 'B' 'A' 'A' 'B' 'B' 'A' 'C' 'A' 'B' 'B' 'B' 'A' 'B' 'B']
 ['C' 'A' 'B' 'A' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A' 'B' 'A' 'B' 'A']]


In [27]:
# création d'une matrice de valeurs aléatoires réelles, distribution uniforme sur [0,1)
print(np.random.rand(4,6))

[[0.15250585 0.58490779 0.15827285 0.68710984 0.55992038 0.76469127]
 [0.51060624 0.28193362 0.3912831  0.58732494 0.0119501  0.75593452]
 [0.67576893 0.15454372 0.54505352 0.15021239 0.90047813 0.78412939]
 [0.75668822 0.32000223 0.92657264 0.487417   0.11852543 0.51114689]]


In [28]:
# idem avec distribution normale (avec moyenne = 0 et écart-type = 1)
print(np.random.normal(0, 1, (4,6)))

[[-0.37420553 -1.32261555  1.25014999  2.09490746 -0.58471258 -0.04419177]
 [ 0.15737824 -0.00512635 -0.61940848 -0.14713127  0.44788934  0.06879132]
 [ 0.42367233  0.3296895  -0.24800177 -1.27784235  0.24949394  0.81331335]
 [ 0.62202164 -0.40214788 -2.79468013  1.90690854 -2.01049581  1.72304731]]


<h2 style="padding:16px; color:#FFF; background:#07D">B - Transformation de matrices</h2>

### 1 - Modification de forme ou de dimension

In [29]:
a = np.array([[1,-2,3,-4], [-5,6,-7,8], [9, -10, 11, -12]]) # création d'une matrice de test
print(a)

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [30]:
print(a.T) # transposition de la matrice (= inversion de l'ordre des dimensions)

[[  1  -5   9]
 [ -2   6 -10]
 [  3  -7  11]
 [ -4   8 -12]]


In [31]:
print(a.ravel()) # aplatissement de la matrice (= conversion en vecteur)

[  1  -2   3  -4  -5   6  -7   8   9 -10  11 -12]


In [32]:
print(a.T.ravel()) # idem avec inversion de l'ordre des dimensions

[  1  -5   9  -2   6 -10   3  -7  11  -4   8 -12]


In [33]:
print(a.repeat(3)) # aplatissement avec répétition

[  1   1   1  -2  -2  -2   3   3   3  -4  -4  -4  -5  -5  -5   6   6   6
  -7  -7  -7   8   8   8   9   9   9 -10 -10 -10  11  11  11 -12 -12 -12]


In [34]:
print(a.T.repeat(3)) # idem avec inversion de l'ordre des dimensions

[  1   1   1  -5  -5  -5   9   9   9  -2  -2  -2   6   6   6 -10 -10 -10
   3   3   3  -7  -7  -7  11  11  11  -4  -4  -4   8   8   8 -12 -12 -12]


In [35]:
print(a.reshape((1,12))) # modification de la forme d'une matrice (1 ligne, 12 colonnes)

[[  1  -2   3  -4  -5   6  -7   8   9 -10  11 -12]]


In [36]:
print(a.reshape((12,1))) # idem (12 lignes, 1 colonne)

[[  1]
 [ -2]
 [  3]
 [ -4]
 [ -5]
 [  6]
 [ -7]
 [  8]
 [  9]
 [-10]
 [ 11]
 [-12]]


In [37]:
print(a.reshape((2,6))) # idem (2 lignes, 6 colonnes)

[[  1  -2   3  -4  -5   6]
 [ -7   8   9 -10  11 -12]]


In [38]:
print(a.reshape((2,2,3))) # idem (2 plans, 2 lignes, 3 colonnes)

[[[  1  -2   3]
  [ -4  -5   6]]

 [[ -7   8   9]
  [-10  11 -12]]]


In [39]:
# si on met -1 pour une dimension, sa taille sera calculée automatiquement
print(a.reshape((2,-1,2))) # idem (2 plans, 3 lignes, 2 colonnes)

[[[  1  -2]
  [  3  -4]
  [ -5   6]]

 [[ -7   8]
  [  9 -10]
  [ 11 -12]]]


In [40]:
print(a[None, :, :]) # ajout d'une dimension en tête
# a[None, ...] # version alternative : '...' représente toutes les dimensions restantes

[[[  1  -2   3  -4]
  [ -5   6  -7   8]
  [  9 -10  11 -12]]]


In [41]:
print(a[:, None, :]) # ajout d'une dimension au centre

[[[  1  -2   3  -4]]

 [[ -5   6  -7   8]]

 [[  9 -10  11 -12]]]


In [42]:
print(a[:, :, None]) # ajout d'une dimension en queue
# a[..., None]) # version alternative : '...' représente toutes les dimensions restantes

[[[  1]
  [ -2]
  [  3]
  [ -4]]

 [[ -5]
  [  6]
  [ -7]
  [  8]]

 [[  9]
  [-10]
  [ 11]
  [-12]]]


---
### 2 - Transformations particulières pour matrice 2D

In [43]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [44]:
print(np.fliplr(a)) # transposition left <-> right

[[ -4   3  -2   1]
 [  8  -7   6  -5]
 [-12  11 -10   9]]


In [45]:
print(np.flipud(a)) # transposition up <-> down

[[  9 -10  11 -12]
 [ -5   6  -7   8]
 [  1  -2   3  -4]]


In [46]:
print(np.rot90(a)) # rotation 90° (sens trigonométrique)

[[ -4   8 -12]
 [  3  -7  11]
 [ -2   6 -10]
 [  1  -5   9]]


In [47]:
print(np.rot90(a,2)) # rotation 180°

[[-12  11 -10   9]
 [  8  -7   6  -5]
 [ -4   3  -2   1]]


In [48]:
print(np.rot90(a,3)) # rotation 270°

[[  9  -5   1]
 [-10   6  -2]
 [ 11  -7   3]
 [-12   8  -4]]


---
### 3 - Répétition, assemblage et découpage de matrices

In [49]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [50]:
print(np.tile(a,[2,3])) # répétition de la matrice (2x en vertical, 3x en horizontal)

[[  1  -2   3  -4   1  -2   3  -4   1  -2   3  -4]
 [ -5   6  -7   8  -5   6  -7   8  -5   6  -7   8]
 [  9 -10  11 -12   9 -10  11 -12   9 -10  11 -12]
 [  1  -2   3  -4   1  -2   3  -4   1  -2   3  -4]
 [ -5   6  -7   8  -5   6  -7   8  -5   6  -7   8]
 [  9 -10  11 -12   9 -10  11 -12   9 -10  11 -12]]


In [51]:
print(np.vstack([a,-a,a])) # assemblage verticale (= en hauteur)
# version alternative : np.concatenate([a,-a,a], axis=0)

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]
 [ -1   2  -3   4]
 [  5  -6   7  -8]
 [ -9  10 -11  12]
 [  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [52]:
print(np.hstack([a,-a,a])) # assemblage horizontale (= en largeur)
# version alternative : np.concatenate([a,-a,a], axis=1)

[[  1  -2   3  -4  -1   2  -3   4   1  -2   3  -4]
 [ -5   6  -7   8   5  -6   7  -8  -5   6  -7   8]
 [  9 -10  11 -12  -9  10 -11  12   9 -10  11 -12]]


In [53]:
print(np.stack([a,-a,a])) # assemblage sur un nouvel axe (= en profondeur)

[[[  1  -2   3  -4]
  [ -5   6  -7   8]
  [  9 -10  11 -12]]

 [[ -1   2  -3   4]
  [  5  -6   7  -8]
  [ -9  10 -11  12]]

 [[  1  -2   3  -4]
  [ -5   6  -7   8]
  [  9 -10  11 -12]]]


In [54]:
print(np.dstack([a,-a,a])) # assemblage par position d'élément

[[[  1  -1   1]
  [ -2   2  -2]
  [  3  -3   3]
  [ -4   4  -4]]

 [[ -5   5  -5]
  [  6  -6   6]
  [ -7   7  -7]
  [  8  -8   8]]

 [[  9  -9   9]
  [-10  10 -10]
  [ 11 -11  11]
  [-12  12 -12]]]


In [55]:
b = np.vstack([a,-a]); c, d, e = np.vsplit(b, 3) # découpage vertical (en parties équitables)
show("b#; c#; d#; e#")

b ━►
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]
 [ -1   2  -3   4]
 [  5  -6   7  -8]
 [ -9  10 -11  12]]
c ━►
[[ 1 -2  3 -4]
 [-5  6 -7  8]]
d ━►
[[  9 -10  11 -12]
 [ -1   2  -3   4]]
e ━►
[[  5  -6   7  -8]
 [ -9  10 -11  12]]


In [56]:
b = np.hstack([a,-a,a]); c, d, e = np.hsplit(b, [3,10]) # découpage horizontal (en parties ajustables)
show("b#; c#; d#; e#")

b ━►
[[  1  -2   3  -4  -1   2  -3   4   1  -2   3  -4]
 [ -5   6  -7   8   5  -6   7  -8  -5   6  -7   8]
 [  9 -10  11 -12  -9  10 -11  12   9 -10  11 -12]]
c ━►
[[  1  -2   3]
 [ -5   6  -7]
 [  9 -10  11]]
d ━►
[[ -4  -1   2  -3   4   1  -2]
 [  8   5  -6   7  -8  -5   6]
 [-12  -9  10 -11  12   9 -10]]
e ━►
[[  3  -4]
 [ -7   8]
 [ 11 -12]]


<h2 style="padding:16px; color:#FFF; background:#07D">C - Accès aux éléments d'une matrice</h2>

### 1 - Accès aux éléments par indices, par tranches et par énumérations

In [57]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [58]:
show("a[0,0]; a[0,-1]; a[2,2]; a[-1,-1];; a[0,(3,1,2,0)]; a[5*(0,1,2),-1]; a[(0,1,1,2),(3,1,2,0)];")
show("a[1,:]; a[:,-1];; a[:,(3,1,2,0)]#;; a[(0,1,1,2),:]#;; a[1:3,1:-1]#;; a[::-1,::-1]#")

a[0,0] ━► 1
a[0,-1] ━► -4
a[2,2] ━► 11
a[-1,-1] ━► -12

a[0,(3,1,2,0)] ━► [-4 -2  3  1]
a[5*(0,1,2),-1] ━► [ -4   8 -12  -4   8 -12  -4   8 -12  -4   8 -12  -4   8 -12]
a[(0,1,1,2),(3,1,2,0)] ━► [-4  6 -7  9]

a[1,:] ━► [-5  6 -7  8]
a[:,-1] ━► [ -4   8 -12]

a[:,(3,1,2,0)] ━►
[[ -4  -2   3   1]
 [  8   6  -7  -5]
 [-12 -10  11   9]]

a[(0,1,1,2),:] ━►
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]

a[1:3,1:-1] ━►
[[  6  -7]
 [-10  11]]

a[::-1,::-1] ━►
[[-12  11 -10   9]
 [  8  -7   6  -5]
 [ -4   3  -2   1]]


---
### 2 - Accès aux éléments par prédicats et méthodes

In [59]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [60]:
show("a[a > 0]; a[abs(a) > 5]; a[(a > 0) & (a < 7)]; a[(a%2 == 0) | (a%3 == 0)]")

a[a > 0] ━► [ 1  3  6  8  9 11]
a[abs(a) > 5] ━► [  6  -7   8   9 -10  11 -12]
a[(a > 0) & (a < 7)] ━► [1 3 6]
a[(a%2 == 0) | (a%3 == 0)] ━► [ -2   3  -4   6   8   9 -10 -12]


In [61]:
b, c = a.copy(), a.copy() # création de deux copies de la matrice 'a'
b[b < 0] = 0 # mettre à 0 tous les éléments strictement négatifs
c[c % 2 != 0] *= 2 # multiplier par 2 tous les éléments impairs
show("b#;; c#")

b ━►
[[ 1  0  3  0]
 [ 0  6  0  8]
 [ 9  0 11  0]]

c ━►
[[  2  -2   6  -4]
 [-10   6 -14   8]
 [ 18 -10  22 -12]]


In [62]:
show("np.where(a < 0, 0, a)#;; np.where(a % 2 != 0, 2*a, a)#") # idem avec création à la volée

np.where(a < 0, 0, a) ━►
[[ 1  0  3  0]
 [ 0  6  0  8]
 [ 9  0 11  0]]

np.where(a % 2 != 0, 2*a, a) ━►
[[  2  -2   6  -4]
 [-10   6 -14   8]
 [ 18 -10  22 -12]]


---
### 3 - Itération sur les éléments

In [63]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [64]:
for value in a: # iteration sur l'axe majeur (= lignes pour matrice 2D)
  print(f"value = {value}")

value = [ 1 -2  3 -4]
value = [-5  6 -7  8]
value = [  9 -10  11 -12]


In [65]:
for value in a.T: # iteration sur l'axe mineur (= colonnes pour matrice 2D)
  print(f"value = {value}")

value = [ 1 -5  9]
value = [ -2   6 -10]
value = [ 3 -7 11]
value = [ -4   8 -12]


In [66]:
for value in a.flat: # iteration avec aplatissement de la matrice
  print(f"value = {value}")
# on peut également itérer sur a.T.flat pour un parcours par colonnes

value = 1
value = -2
value = 3
value = -4
value = -5
value = 6
value = -7
value = 8
value = 9
value = -10
value = 11
value = -12


In [67]:
for index, value in enumerate(a.flat): # iteration avec index 1D
  print(f"index = {index} ● value = {value}") # access with a.flat[index]

index = 0 ● value = 1
index = 1 ● value = -2
index = 2 ● value = 3
index = 3 ● value = -4
index = 4 ● value = -5
index = 5 ● value = 6
index = 6 ● value = -7
index = 7 ● value = 8
index = 8 ● value = 9
index = 9 ● value = -10
index = 10 ● value = 11
index = 11 ● value = -12


In [68]:
for index, value in np.ndenumerate(a): # iteration avec index nD
  print(f"index = {index} ● value = {value}") # access with a[index]

index = (0, 0) ● value = 1
index = (0, 1) ● value = -2
index = (0, 2) ● value = 3
index = (0, 3) ● value = -4
index = (1, 0) ● value = -5
index = (1, 1) ● value = 6
index = (1, 2) ● value = -7
index = (1, 3) ● value = 8
index = (2, 0) ● value = 9
index = (2, 1) ● value = -10
index = (2, 2) ● value = 11
index = (2, 3) ● value = -12


<h2 style="padding:16px; color:#FFF; background:#07D">D - Opérations sur les matrices</h2>

### 1 - Manipulation par opérateurs

Les opérateurs arithmétiques standards **`+  -  *  /  //  %  ** `** sont utilisables sur les matrices multidimensionnelles de type **`array`**. Ces opérateurs s'appliquent toujours ***élément par élément***, sur les deux matrices utilisées comme opérandes. A ces opérateurs standards, s'ajoute également l'opérateur **`@`** qui permet d'effectuer un ***produit matriciel*** entre deux matrices.

Lors de l'application de l'opérateur, l'interpréteur va vérifier le paramètre **`shape`** (nombre d'éléments dans chaque dimension) des deux matrices pour savoir si l'opération choisie est possible. Si les valeurs de **`shape`** sont identiques pour les deux matrices, l'opérations va s'effectuer élément par élément, sans difficulté. Si les valeurs de **`shape`** sont différentes, mais que pour chaque dimension, le nombre d'éléments est soit le même pour les deux matrices, soit égal à 0 ou 1 pour l'une des matrices, l'opération est également possible grâce au principe du ***broadcasting*** mis en oeuvre par **`numpy`**. Cela consiste à répéter les données automatiquement les données existantes pour obtenir autant d'éléments sur chaque dimension que l'autre opérande. Le principe du broadcasting est assez intuitif, mais des explications détaillées sont disponibles sur [**cette page**](https://numpy.org/doc/stable/user/basics.broadcasting.html) du manuel d'utilisation de **`numpy`**.

In [69]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [70]:
show("a + a#;; a * a#;; a % 4#;; a ** 4#;; 4 - 3*a + 2*a*a#") # opérateurs avec ou sans broadcasting

a + a ━►
[[  2  -4   6  -8]
 [-10  12 -14  16]
 [ 18 -20  22 -24]]

a * a ━►
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

a % 4 ━►
[[1 2 3 0]
 [3 2 1 0]
 [1 2 3 0]]

a ** 4 ━►
[[    1    16    81   256]
 [  625  1296  2401  4096]
 [ 6561 10000 14641 20736]]

4 - 3*a + 2*a*a ━►
[[  3  18  13  48]
 [ 69  58 123 108]
 [139 234 213 328]]


In [71]:
show("a @ a.T#;; a.T @ a#") # produit matriciel

a @ a.T ━►
[[  30  -70  110]
 [ -70  174 -278]
 [ 110 -278  446]]

a.T @ a ━►
[[ 107 -122  137 -152]
 [-122  140 -158  176]
 [ 137 -158  179 -200]
 [-152  176 -200  224]]


---
Chacun des opérateurs arithmétiques **`+  -  *  /  //  %  **  @`** possède son équivalent sous forme de fonction : **`np.add, np.subtract, np.multiply, np.divide, np.floor_divide, np.mod, np.power, np.matmul`** . L'intérêt principal d'avoir cette double syntaxe est de pouvoir utiliser les opérateurs en tant que paramètre d'une fonction (ce qui peut s'avérer utile de temps en temps) mais également d'utiliser des paramètres optionnels permettant d'obtenir des modes supplémentaires pour les calculs. Par exemple, on peut utiliser le mode **`outer`** (mode externe, plus communément appelé, ***mode cartésien***) pour les opérations sur les vecteurs et les matrices, au lieu du mode **`inner`** (mode interne, autrement dit, ***élément par élément***) mis en oeuvre par défaut :

In [72]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [73]:
show("np.add(a, a)#;; np.mod(a, 4)#;; np.matmul(a, a.T)#")

np.add(a, a) ━►
[[  2  -4   6  -8]
 [-10  12 -14  16]
 [ 18 -20  22 -24]]

np.mod(a, 4) ━►
[[1 2 3 0]
 [3 2 1 0]
 [1 2 3 0]]

np.matmul(a, a.T) ━►
[[  30  -70  110]
 [ -70  174 -278]
 [ 110 -278  446]]


In [74]:
z = np.arange(11) # création d'un vecteur de test
show("z;; np.add.outer(z, z)#;; np.multiply.outer(z[1:], z[1:])#") # utilisation du mode cartésien

z ━► [ 0  1  2  3  4  5  6  7  8  9 10]

np.add.outer(z, z) ━►
[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10 11]
 [ 2  3  4  5  6  7  8  9 10 11 12]
 [ 3  4  5  6  7  8  9 10 11 12 13]
 [ 4  5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14 15]
 [ 6  7  8  9 10 11 12 13 14 15 16]
 [ 7  8  9 10 11 12 13 14 15 16 17]
 [ 8  9 10 11 12 13 14 15 16 17 18]
 [ 9 10 11 12 13 14 15 16 17 18 19]
 [10 11 12 13 14 15 16 17 18 19 20]]

np.multiply.outer(z[1:], z[1:]) ━►
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


---
Les opérateurs de comparaison **`==  !=  >  >=  <  <=`** peuvent également être utilisées sur les données de type **`array`** et renvoient une matrice de booléens, en effectuant la comparaison élément par élément. Comme pour les opérateurs arithmétiques, chaque opérateur de comparaison possède son équivalent sous forme de fonction : **`np.equal, np.not_equal, np.greater, np.greater_equal, np.less, np.less_equal`**. Les expressions booléennes résultant des comparaisons peuvent se combiner avec les opérateurs booléens classiques **`!  &  |  ^`**, qui eux-même possèdent leur équivalent fonctionnel : **`np.logical_not, np.logical_or, np.logical_and, np.logical_xor`** :

In [75]:
show("a > 0#;; np.less_equal(a, 0)#;")
show("(a <= -8) | (a >= 2)#;; np.logical_and(np.greater(a,-8), np.less(a,2))#;")
show("np.less.outer(a.flat, z)#")

a > 0 ━►
[[ True False  True False]
 [False  True False  True]
 [ True False  True False]]

np.less_equal(a, 0) ━►
[[False  True False  True]
 [ True False  True False]
 [False  True False  True]]

(a <= -8) | (a >= 2) ━►
[[False False  True False]
 [False  True False  True]
 [ True  True  True  True]]

np.logical_and(np.greater(a,-8), np.less(a,2)) ━►
[[ True  True False  True]
 [ True False  True False]
 [False False False False]]

np.less.outer(a.flat, z) ━►
[[False False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [False False False False  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [False False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [False False False False False False False False F

---
### 2 - Manipulation par fonctions universelles

En plus du conteneur **`array`** particulièrement flexible et efficace, l'autre apport majeur du package **`numpy`** consiste en une nouvelle famille de fonctions **`ufunc`**, appelées ***fonctions universelles***. La propriété commune de ces fonctions est qu'elles peuvent s'appliquer directement à des vecteurs ou des matrices multi-dimensionnelles, et qu'elles vont automatiquement générer une boucle permettant d'appliquer la fonction, élément par élément, sur l'ensemble de la structure. Ce processus, appelé **vectorisation**, permet non seulement d'écrire un code plus compact (proche de la notation algébrique utilisée en mathématiques) mais surtout beaucoup plus rapide qu'un code en Python pur (entre 20x et 30x plus rapide, en moyenne).

Parmi les fonctions universelles fournies par **`numpy`**, on trouve notament les versions universelles des fonctions mathématiques figurant dans le module **`math`** standard de Python :

**`abs`** ● **`sign`** ● **`floor`** ● **`ceil`** ● **`round`** ● **`deg2rad`** ● **`rad2deg`** ● **`real`** ● **`imag`** ● **`hypot`** ● **`angle`** ● **`sqrt`** ● **`exp`** ● **`log`** ● **`log2`** ● **`log10`** ● **`cos`** ● **`sin`** ● **`tan`** ● **`arccos`** ● **`arcsin`** ● **`arctan`** ● **`arctan2`** ● **`cosh`** ● **`sinh`** ● **`tanh`** ● **`arccosh`** ● **`arcsinh`** ● **`arctanh`** ● **`nonzero`** ● **`isclose`** ● **`isfinite`** ● **`isinf`** ● **`isnan`**

In [76]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [77]:
show("np.abs(a)#;; np.sign(a)#;; np.exp(np.sin(a))#") # utilisation de fonctions universelles

np.abs(a) ━►
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.sign(a) ━►
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]

np.exp(np.sin(a)) ━►
[[2.31977682 0.40280713 1.15156284 2.13144999]
 [2.60888852 0.75622563 0.51841116 2.68950792]
 [1.51001334 1.72292101 0.36788304 1.71013603]]


---
Les fonctions précédentes s'appliquent élément par élément, et renvoient donc systématiquement une matrice ayant la même taille que la matrice de départ. Il existent une seconde catégorie de fonctions de manipulation, qui vont effectuer des traitements divers sur une partie des données de la matrice, et renvoyer le résultat de ces traitements, qui pourra être soit un scalaire, soit un vecteur, soit une matrice de taille ou de dimension différente de celle de départ. La plupart de ces fonctions possèdent un argument optionnel **`axis`** qui permet de choisir la dimension (*lignes, colonnes, plans, etc*) le long de laquelle doit s'effectuer le traitement (par défaut, celui-ci s'effectue sur l'ensemble de la matrice)

In [78]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [79]:
print(np.diag(a)) # extraction de diagonale

[ 1  6 11]


In [80]:
print(np.diag(a, 2)) # extraction de diagonale avec décalage

[3 8]


In [81]:
print(np.tril(a)) # extraction du triangle inférieur

[[  1   0   0   0]
 [ -5   6   0   0]
 [  9 -10  11   0]]


In [82]:
print(np.triu(a, 2)) # extraction du triangle supérieur avec décalage

[[ 0  0  3 -4]
 [ 0  0  0  8]
 [ 0  0  0  0]]


In [83]:
show("np.max(a); np.max(a, axis=0); np.min(a); np.min(a, axis=1); np.ptp(a);") # ptp = peak to peak
show("np.argmax(a); np.argmax(a, axis=0); np.argmin(a); np.argmin(a, axis=1)")

np.max(a) ━► 11
np.max(a, axis=0) ━► [ 9  6 11  8]
np.min(a) ━► -12
np.min(a, axis=1) ━► [ -4  -7 -12]
np.ptp(a) ━► 23

np.argmax(a) ━► 10
np.argmax(a, axis=0) ━► [2 1 2 1]
np.argmin(a) ━► 11
np.argmin(a, axis=1) ━► [3 2 3]


In [84]:
show("np.sum(a, axis=0); np.cumsum(a, axis=1)#;; np.prod(a, axis=0); np.cumprod(a, axis=1)#;")
show("np.mean(a, axis=1); np.average(a, axis=1, weights=[1,3,1,3]); np.var(a, axis=1); np.std(a, axis=1);")
show("np.percentile(a, [25,50,75]); np.clip(a, -7, 7)#;") # clip = écrêtage
show("np.sort(a, axis=None); np.sort(a, axis=0)#; np.sort(a, axis=1)#")

np.sum(a, axis=0) ━► [ 5 -6  7 -8]
np.cumsum(a, axis=1) ━►
[[ 1 -1  2 -2]
 [-5  1 -6  2]
 [ 9 -1 10 -2]]

np.prod(a, axis=0) ━► [ -45  120 -231  384]
np.cumprod(a, axis=1) ━►
[[    1    -2    -6    24]
 [   -5   -30   210  1680]
 [    9   -90  -990 11880]]

np.mean(a, axis=1) ━► [-0.5  0.5 -0.5]
np.average(a, axis=1, weights=[1,3,1,3]) ━► [-1.75  3.75 -5.75]
np.var(a, axis=1) ━► [  7.25  43.25 111.25]
np.std(a, axis=1) ━► [ 2.6925824   6.57647322 10.54751155]

np.percentile(a, [25,50,75]) ━► [-5.5 -0.5  6.5]
np.clip(a, -7, 7) ━►
[[ 1 -2  3 -4]
 [-5  6 -7  7]
 [ 7 -7  7 -7]]

np.sort(a, axis=None) ━► [-12 -10  -7  -5  -4  -2   1   3   6   8   9  11]
np.sort(a, axis=0) ━►
[[ -5 -10  -7 -12]
 [  1  -2   3  -4]
 [  9   6  11   8]]
np.sort(a, axis=1) ━►
[[ -4  -2   1   3]
 [ -7  -5   6   8]
 [-12 -10   9  11]]


In [85]:
z = np.random.randint(0, 10, 100) # création d'un vecteur d'entiers aléatoires
zz = np.digitize(z, (2,8)) # quantification en 3 groupes : {0,1}, {2,3,4,5,6,7} {8,9}
show("z#; np.bincount(z);; zz#; np.bincount(zz)") # bincount = histogramme avec bins = 0,1,2...n

z ━►
[9 1 7 6 0 0 7 7 6 2 3 5 3 7 2 3 0 1 5 4 5 7 1 5 7 5 3 2 5 8 5 6 8 5 7 3 9
 8 9 1 1 3 7 9 6 7 0 2 0 8 5 4 7 5 5 1 5 5 2 0 4 3 4 0 2 4 1 4 1 8 3 9 4 4
 6 4 9 3 9 1 1 2 3 7 4 7 5 4 1 1 4 0 0 4 4 1 3 5 3 7]
np.bincount(z) ━► [ 9 13  7 12 14 15  5 13  5  7]

zz ━►
[2 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 2 1 1 2 1 1 1 2
 2 2 0 0 1 1 2 1 1 0 1 0 2 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 0 2 1 2 1 1
 1 1 2 1 2 0 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1]
np.bincount(zz) ━► [22 66 12]


In [86]:
z = np.random.normal(0, 2, 10000) # création d'un vecteur de valeurs aléatoires (distribution normale)
show("np.mean(z); np.std(z)") # la moyenne et l'écart-type sont conformes à la distribution choisie
histoA, binsA = np.histogram(z, range(-9,10,2)) # création d'un histogramme (bins personnalisés)
histoB, binsB = np.histogram(z, [-1000,-5,-3,-1,1,3,5,1000]) # création d'un histogramme (bins variables)
show("histoA; binsA; histoB; binsB")

np.mean(z) ━► 0.013479074072166452
np.std(z) ━► 2.011548072225045
histoA ━► [   5   74  587 2414 3803 2444  611   59    3]
binsA ━► [-9 -7 -5 -3 -1  1  3  5  7  9]
histoB ━► [  79  587 2414 3803 2444  611   62]
binsB ━► [-1000    -5    -3    -1     1     3     5  1000]


---
### 3 - Manipulation par méthodes

Les fonctions de manipulation de matrices les plus utilisées sont directement implémentées sous forme de méthodes, accessibles via la notation pointée, ce qui permet une syntaxe plus compacte lors de leur mise en oeuvre :

In [87]:
print(a) # rappel du contenu de la matrice

[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]


In [88]:
show("a.max(); a.max(axis=0); a.min(); a.min(axis=1); a.ptp();")
show("a.argmax(); a.argmax(axis=0); a.argmin(); a.argmin(axis=1)")

a.max() ━► 11
a.max(axis=0) ━► [ 9  6 11  8]
a.min() ━► -12
a.min(axis=1) ━► [ -4  -7 -12]
a.ptp() ━► 23

a.argmax() ━► 10
a.argmax(axis=0) ━► [2 1 2 1]
a.argmin() ━► 11
a.argmin(axis=1) ━► [3 2 3]


In [89]:
show("a.sum(axis=0); a.cumsum(axis=1)#;; a.prod(axis=0); a.cumprod(axis=1)#;")
show("a.mean(axis=1); a.var(axis=1); a.std(axis=1); a.clip(-7,7)#")

a.sum(axis=0) ━► [ 5 -6  7 -8]
a.cumsum(axis=1) ━►
[[ 1 -1  2 -2]
 [-5  1 -6  2]
 [ 9 -1 10 -2]]

a.prod(axis=0) ━► [ -45  120 -231  384]
a.cumprod(axis=1) ━►
[[    1    -2    -6    24]
 [   -5   -30   210  1680]
 [    9   -90  -990 11880]]

a.mean(axis=1) ━► [-0.5  0.5 -0.5]
a.var(axis=1) ━► [  7.25  43.25 111.25]
a.std(axis=1) ━► [ 2.6925824   6.57647322 10.54751155]
a.clip(-7,7) ━►
[[ 1 -2  3 -4]
 [-5  6 -7  7]
 [ 7 -7  7 -7]]


---
### 4 - Création de fonctions universelles

En plus du catalogue de fonctions universelles prédéfinies, **`numpy`** fournit un mécanisme permettant de convertir très simplement une fonction classique (= applicable à des données scalaires) en une fonction universelle (= applicable à des données matricielles et bénéficiant du processus de vectorisation). Après avoir écrit le code de la fonction classique, la conversion se réalise en appelant la fonction **`np.frompyfunc(func, nin, nout)`** où **`func`** correspond au nom de la fonction qu'on souhaite vectoriser, **`nin`** et **`nout`** correspondent respectivement au nombre d'arguments en entrée et en sortie pour la fonction **`func`**.

Voici un exemple de mise en oeuvre, avec la fonction **`facto`** :

In [90]:
def facto(n): # définition d'une fonction classique
  """return n! (factorial of integer n >= 0)"""
  out = 1
  for loop in range(1, n+1): out *= loop
  return out

In [91]:
ufacto = np.frompyfunc(facto, 1, 1) # conversion en fonction universelle
show("type(facto); type(ufacto)")

type(facto) ━► <class 'function'>
type(ufacto) ━► <class 'numpy.ufunc'>


In [92]:
z = np.arange(21) # création d'un vecteur d'entiers de 0 à 20
print(np.stack([z, ufacto(z)]).T) # application de la fonction sur le vecteur 'z'

[[0 1]
 [1 1]
 [2 2]
 [3 6]
 [4 24]
 [5 120]
 [6 720]
 [7 5040]
 [8 40320]
 [9 362880]
 [10 3628800]
 [11 39916800]
 [12 479001600]
 [13 6227020800]
 [14 87178291200]
 [15 1307674368000]
 [16 20922789888000]
 [17 355687428096000]
 [18 6402373705728000]
 [19 121645100408832000]
 [20 2432902008176640000]]


---